import {
  Check, ClipboardText, DotsThree, DownloadSimple, PencilSimple, ShareNetwork, Trash, WarningCircle,
} from '@phosphor-icons/react';
import { useEffect, useState, type ReactNode } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { isContentDoc, type Block, type ContentDoc, type FigureSpec } from '../../api/content';
import { useAIUnavailable } from '../../api/core';
import {
  downloadMaterial, useDeleteBlock, useDeleteMaterial, useMaterial, useMaterialToActivity, usePatchBlock, useRetryMaterial,
  useRewriteBlock, useUpdateMaterial, type MaterialDetail,
} from '../../api/units';
import EditMaterialSheet from '../../features/materials/EditMaterialSheet';
import FigureSheet from '../../features/materials/FigureSheet';
import { STEPS, useGeneration } from '../../features/materials/progress';
import ShareSheet from '../../features/materials/ShareSheet';
import { useWatched, watchJob } from '../../features/materials/watch';
import { failedText, isDraft, readyText, shortTitle, withArticle } from '../../features/units/kinds';
import { ApiError } from '../../lib/api';
import { useToday } from '../../lib/auth';
import { longDate, ordinals, plural } from '../../lib/format';
import {
  AIBadge, Button, Callout, Dot, EmptyState, IconButton, Menu, Page, Progress, Segmented, SkeletonList, Spinner, TextSubsProvider,
  useFeedback, type MenuItem,
} from '../../ui';
import { figureCaption } from './blocks';
import DocView, { docOutline } from './DocView';
import EditElementSheet from './EditElementSheet';
import type { ElementAction } from './ElementMenu';
import { Problems, ReviewNotes, scrollToElement } from './materialParts';
import Presentation from './Presentation';
import RewriteSheet from './RewriteSheet';
import './MaterialPage.css';

type Editing = { action: 'edit' | 'rewrite' | 'figure' | 'solution_figure'; el: Block } | null;
type Variant = 'pdf' | 'key';

/** Material generated by Sepia: the ContentDoc on paper (apuntes, ficha, resumen, lectura sencilla) with its downloads,
 *  «Editar» (each block: its text, its figure, an AI rewrite, remove) and «Marcar como revisado», or a presentation
 *  (Presentation). While it is created it shows the stage; if it failed, «Volver a intentar». */
export default function MaterialPage() {
  const { courseId = '', unitId = '', materialId = '' } = useParams();
  const { data: m, isLoading, error, refetch } = useMaterial(materialId);
  const unitPath = `/clases/${courseId}/unidades/${unitId}`;

  if (error) {
    const missing = error instanceof ApiError && error.status === 404;
    return (
      <Page title="Material" back={unitPath} backLabel="Unidad" backToOrigin>
        <EmptyState icon={<WarningCircle size={24} />} title={missing ? 'No se ha encontrado el material' : 'No se ha podido cargar el material'}
          text={(error as Error).message}
          action={missing
            ? <Button variant="neutral" to={unitPath}>Volver a la unidad</Button>
            : <Button variant="tinted" onClick={() => refetch()}>Reintentar</Button>} />
      </Page>
    );
  }
  if (isLoading || !m) return <Page title="" back={unitPath} backLabel="Unidad" backToOrigin><SkeletonList rows={6} /></Page>;
  return <Material m={m} courseId={courseId} unitPath={unitPath} />;
}

function Material({ m, courseId, unitPath }: { m: MaterialDetail; courseId: string; unitPath: string }) {
  const navigate = useNavigate();
  const today = useToday();
  const noAI = useAIUnavailable();
  const { toast, confirm } = useFeedback();
  const del = useDeleteMaterial(m.unit_id ?? undefined);
  const update = useUpdateMaterial();
  const toActivity = useMaterialToActivity(m.id);
  const patchBlock = usePatchBlock(m.id);
  const deleteBlock = useDeleteBlock(m.id);
  const rewrite = useRewriteBlock(m.id);
  const [params] = useSearchParams();
  const [renaming, setRenaming] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editing, setEditing] = useState<Editing>(null);
  const [solutions, setSolutions] = useState(false);
  const [downloading, setDownloading] = useState<Variant | null>(null);
  const watched = useWatched();
  const busy = new Set(watched.flatMap((w) => (w.kind === 'rewrite' && w.materialId === m.id ? [w.blockId] : [])));

  const doc: ContentDoc | null = isContentDoc(m.content) ? m.content : null;
  // From Hoy, apuntes open at the first section of the lesson the class is at (?sesion=k).
  const lessonSection = doc?.kind !== 'presentacion' ? doc?.sections.find((sec) => sec.lesson === Number(params.get('sesion'))) : undefined;
  useEffect(() => {
    if (!lessonSection) return undefined;
    const t = window.setTimeout(() => document.getElementById(`sec-${lessonSection.id}`)?.scrollIntoView({ block: 'start' }), 100);
    return () => window.clearTimeout(t);
  }, [lessonSection]);

  const unitTitle = m.unit_title ?? '';
  const title = shortTitle(m.title, unitTitle);
  const path = `${unitPath}/materiales/${m.id}`;

  const page = { back: unitPath, backLabel: unitTitle || 'Unidad', backToOrigin: true };
  const eyebrow = <><Dot color={m.course.color} /><span className="eyebrow">{ordinals(m.course.label)}</span></>;

  const remove = async () => {
    const ok = await confirm({
      title: `¿Eliminar «${title}»?`,
      text: `Se borrarán también sus archivos.${m.shared ? ' El enlace para alumnos y su código QR dejarán de funcionar.' : ''} No se puede deshacer.`,
      confirm: 'Eliminar', danger: true,
    });
    if (!ok) return;
    try {
      await del.mutateAsync(m.id);
      toast('Material eliminado');
      navigate(unitPath, { replace: true });
    } catch (e) {
      toast((e as Error).message, { tone: 'error' });
    }
  };

  if (m.status === 'generating') {
    return <Page title={title} eyebrow={eyebrow} {...page}><Generating m={m} /></Page>;
  }
  if (m.status === 'failed') return <Failed m={m} title={title} eyebrow={eyebrow} page={page} unitTitle={unitTitle} path={path} onRemove={remove} />;

  const download = async (variant: Variant) => {
    setDownloading(variant);
    try {
      await downloadMaterial(m.id, variant);
    } catch (e) {
      toast((e as Error).message, { tone: 'error' });
    } finally {
      setDownloading(null);
    }
  };

  const markReviewed = () => update.mutate({ id: m.id, reviewed: true }, {
    onSuccess: () => toast('Marcado como revisado'), onError: (e) => toast((e as Error).message, { tone: 'error' }),
  });

  const evaluate = async () => {
    const ok = await confirm({
      title: 'Evaluar esta ficha',
      text: `Se añade una columna «${m.title}» al cuaderno con fecha de hoy (${longDate(today)}) y la rúbrica de la ficha. Podrás cambiar la fecha y la nota máxima.`,
      confirm: 'Añadir al cuaderno',
    });
    if (!ok) return;
    try {
      const { activity_id } = await toActivity.mutateAsync({ date: today, max_score: 10 });
      toast('Ficha añadida al cuaderno');
      navigate(`/clases/${courseId}/actividades/${activity_id}`);
    } catch (e) {
      toast((e as Error).message, { tone: 'error' });
    }
  };

  const menu: MenuItem[] = [
    { label: 'Renombrar', icon: <PencilSimple size={18} />, onSelect: () => setRenaming(true) },
    { label: 'Compartir con alumnos', icon: <ShareNetwork size={18} />, onSelect: () => setSharing(true) },
    ...(m.kind === 'worksheet' ? [{ label: 'Evaluar esta ficha', icon: <ClipboardText size={18} />, onSelect: evaluate }] : []),
    { label: 'Eliminar', icon: <Trash size={18} />, danger: true, separatorBefore: true, onSelect: remove },
  ];
  const sheets = (
    <>
      {renaming && <EditMaterialSheet material={m} onClose={() => setRenaming(false)} />}
      {sharing && <ShareSheet material={m} onClose={() => setSharing(false)} />}
    </>
  );

  if (doc?.kind === 'presentacion') {
    return <><Presentation m={m} doc={doc} title={title} eyebrow={eyebrow} page={page} menu={menu} path={path} />{sheets}</>;
  }

  const what = (el: Block) => (el.type === 'exercise' ? 'Ejercicio' : 'Apartado');
  const onAction = async (action: ElementAction, el: Block) => {
    if (action !== 'remove') { setEditing({ action, el }); return; }
    const ok = await confirm({
      title: `¿Quitar este ${what(el).toLowerCase()}?`,
      text: 'Desaparece de la vista, del PDF y de las descargas. Si otro apartado lo menciona, edítalo después.',
      confirm: 'Quitar', danger: true,
    });
    if (!ok) return;
    deleteBlock.mutate(el.id, {
      onSuccess: () => toast(`${what(el)} quitado`), onError: (e) => toast((e as Error).message, { tone: 'error' }),
    });
  };
  const save = (el: Block) => patchBlock.mutate(el, {
    onSuccess: () => { toast('Cambios guardados'); setEditing(null); },
    onError: (e) => toast((e as Error).message, { tone: 'error' }),
  });
  const saveFigure = (el: Block, key: 'figure' | 'solution_figure', spec: FigureSpec, caption?: string) =>
    save({ ...el, [key]: spec, ...(caption !== undefined ? { caption } : {}) } as Block);
  const sendRewrite = (el: Block, instruction: string) => rewrite.mutate({ blockId: el.id, instruction }, {
    onSuccess: ({ job }) => {
      watchJob({ job: job.id, kind: 'rewrite', materialId: m.id, blockId: el.id, done: `${what(el)} reescrito con IA`, path });
      setEditing(null);
      toast('Reescribiendo con IA. Puedes seguir trabajando.');
    },
    onError: (e) => toast((e as Error).message, { tone: 'error' }),
  });

  // The PDF is what students get (never with solutions); the solucionario is the teacher's.
  const downloads: { variant: Variant; label: string }[] = m.extra_url
    ? [{ variant: 'pdf', label: 'Descargar PDF' }, { variant: 'key', label: 'Descargar solucionario' }]
    : [{ variant: 'pdf', label: 'Descargar PDF' }];
  const hasKey = !!doc && doc.sections.some((s) => s.blocks.some((b) => ['exercise', 'your_turn', 'review', 'case'].includes(b.type)));

  const toolbar = (
    <div className="material-bar material-bar--reading">
      <div className="material-actions">
        {downloads.length === 1
          ? <Button size="sm" icon={<DownloadSimple size={16} />} loading={!!downloading} onClick={() => download('pdf')}>Descargar PDF</Button>
          : <Menu trigger={(open) => (
            <Button size="sm" icon={<DownloadSimple size={16} />} loading={!!downloading} onClick={open}>Descargar</Button>
          )} items={downloads.map((d) => ({ label: d.label, onSelect: () => void download(d.variant) }))} />}
        {doc && (
          <Button size="sm" variant={editMode ? 'tinted' : 'neutral'} icon={editMode ? <Check size={16} weight="bold" /> : <PencilSimple size={16} />}
            onClick={() => setEditMode(!editMode)}>{editMode ? 'Hecho' : 'Editar'}</Button>
        )}
      </div>
      {hasKey && (
        <Segmented label="Soluciones" value={solutions ? 'sol' : 'enun'} onChange={(v) => setSolutions(v === 'sol')}
          options={[{ value: 'enun', label: 'Enunciados' }, { value: 'sol', label: 'Con soluciones' }]} />
      )}
    </div>
  );

  const count = doc && m.kind === 'worksheet'
    ? `${plural(doc.sections.flatMap((s) => s.blocks).filter((b) => b.type === 'exercise').length, 'ejercicio', 'ejercicios')} · con solucionario`
    : null;

  return (
    <Page title={title} eyebrow={eyebrow} {...page}
      subtitle={<>{unitTitle && <span>{unitTitle}</span>}{count && <span>{count}</span>}{isDraft(m) && <AIBadge />}</>}
      actions={<Menu trigger={(open) => <IconButton label="Más opciones" glass onClick={open}><DotsThree size={22} weight="bold" /></IconButton>} items={menu} />}
      toolbar={toolbar}>
      <TextSubsProvider value={{ names: m.names }}>
      <div className="material-layout">
      <div className="material-body material-body--reading">
        {!doc ? (
          <Callout tone="warn">Este material no se puede mostrar ni editar en la app. Descarga el PDF para verlo.</Callout>
        ) : editMode ? (
          <Callout tone="accent" icon={<DotsThree size={20} weight="bold" />}>
            Abre el menú de cada apartado para cambiar su texto o su figura, reescribirlo con IA o quitarlo. Cada cambio se guarda al momento y rehace el PDF.
          </Callout>
        ) : isDraft(m) && (
          <Callout tone="accent">
            <div className="review-note">
              <span>Borrador de la IA: revísalo antes de usarlo en clase.</span>
              <Button size="sm" variant="tinted" icon={<Check size={16} weight="bold" />} loading={update.isPending} onClick={markReviewed}>Marcar como revisado</Button>
            </div>
          </Callout>
        )}
        {doc && <Problems m={m} />}
        {doc && isDraft(m) && <ReviewNotes notes={m.review ?? []} doc={doc} onGo={scrollToElement} />}
        {doc && typeof m.options.coverage_note === 'string' && m.options.coverage_note && (
          <Callout>{m.options.coverage_note} Si quieres una ficha con todas, créala con más ejercicios.</Callout>
        )}
        {doc && <DocView doc={doc} figures={m.figures} solutions={solutions} editing={editMode} busy={busy} onAction={onAction} noAI={noAI} />}
      </div>
      {doc && <Outline doc={doc} />}
      </div>
      </TextSubsProvider>

      {editing?.action === 'edit' && <EditElementSheet el={editing.el} saving={patchBlock.isPending} onSave={save} onClose={() => setEditing(null)} />}
      {editing?.action === 'rewrite' && (
        <RewriteSheet el={editing.el} sending={rewrite.isPending} onSend={(t) => sendRewrite(editing.el, t)} onClose={() => setEditing(null)} />
      )}
      {(editing?.action === 'figure' || editing?.action === 'solution_figure') && (() => {
        const el = editing.el as Block & { figure?: FigureSpec | null; solution_figure?: FigureSpec | null; caption?: string };
        const spec = editing.action === 'figure' ? el.figure : el.solution_figure;
        const caption = editing.action !== 'figure' ? undefined : el.type === 'figure' ? figureCaption(el)
          : 'caption' in el ? el.caption : undefined;  // a figure block shows the caption the PDF prints
        return spec ? (
          <FigureSheet spec={spec} caption={caption} saving={patchBlock.isPending} onClose={() => setEditing(null)}
            onSave={(sp, c) => saveFigure(el, editing.action as 'figure' | 'solution_figure', sp, c)} />
        ) : null;
      })()}
      {sheets}
    </Page>
  );
}

/** Desktop: the sections and exercise numbers beside the document, to jump to them. */
function Outline({ doc }: { doc: ContentDoc }) {
  const entries = docOutline(doc).filter((e) => e.label || e.exercises.length);
  if (entries.length < 2) return null;
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  return (
    <nav className="material-outline" aria-label="Índice del material">
      <div className="material-outline__title">En este material</div>
      <ol>
        {entries.map((e) => (
          <li key={e.id}>
            <button type="button" className="material-outline__link" onClick={() => go(`sec-${e.id}`)}>{e.label || 'Ejercicios'}</button>
            {e.exercises.length > 0 && (
              <div className="material-outline__nums">
                {e.exercises.map((n) => (
                  <button key={n} type="button" className="material-outline__num num" onClick={() => go(`ex-${n}`)}
                    aria-label={`Ejercicio ${n}`}>{n}</button>
                ))}
              </div>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}

/** Creating: the pipeline's stages, the current one marked (1-4 minutes; the teacher can leave). */
function Generating({ m }: { m: MaterialDetail }) {
  const g = useGeneration(m);
  return (
    <div className="paper material-wait" role="status">
      <Spinner />
      <div className="material-wait__title">Creando {withArticle(m)}</div>
      {g.step > 0 ? (
        <>
          <ol className="material-steps">
            {STEPS.map((s, i) => <li key={s} className={i + 1 < g.step ? 'done' : i + 1 === g.step ? 'now' : undefined}>{s.replace('…', '')}</li>)}
          </ol>
          <Progress value={g.step} total={STEPS.length} />
        </>
      ) : <p className="muted">{g.text}</p>}
      <p className="muted">Tarda unos minutos. Puedes salir y seguir trabajando: al terminar aparece un aviso.</p>
    </div>
  );
}

function Failed({ m, title, eyebrow, page, unitTitle, path, onRemove }: {
  m: MaterialDetail; title: string; eyebrow: ReactNode; page: { back: string; backLabel: string; backToOrigin: boolean };
  unitTitle: string; path: string; onRemove: () => void;
}) {
  const retry = useRetryMaterial();
  const noAI = useAIUnavailable();
  const { toast } = useFeedback();
  const again = () => retry.mutate(m.id, {
    onSuccess: ({ material, job }) => {
      watchJob({
        job: job.id, kind: 'material', done: readyText(material, unitTitle), failed: failedText(material, unitTitle), path,
      });
      toast(`Creando ${withArticle(material)} otra vez`);
    },
    onError: (e) => toast((e as Error).message, { tone: 'error' }),
  });
  return (
    <Page title={title} eyebrow={eyebrow} {...page}>
      <div className="paper">
        <EmptyState icon={<WarningCircle size={24} />} title="No se ha podido crear" text={m.error ?? 'Vuelve a intentarlo.'}
          action={<div className="material-actions">
            <Button onClick={again} loading={retry.isPending} disabled={!!noAI}>{noAI ?? 'Volver a intentar'}</Button>
            <Button variant="danger" onClick={onRemove}>Eliminar</Button>
          </div>} />
      </div>
    </Page>
  );
}
