import {
  ClipboardText, Eyeglasses, FileText, GoogleDriveLogo, ImageSquare, LinkSimple, MonitorPlay, Notebook, PaintBrush, Paperclip,
  PresentationChart, PuzzlePiece, TextAlignLeft, YoutubeLogo,
} from '@phosphor-icons/react';
import type { LinkKind, Material, MaterialKind } from '../../api/units';

/** Line icon for a material kind (uploads: by file extension; links: by site). */
export function MaterialIcon({ kind, filename, linkKind, size = 20 }: {
  kind: MaterialKind; filename?: string; linkKind?: LinkKind | null; size?: number;
}) {
  switch (kind) {
    case 'notes': return <Notebook size={size} />;
    case 'slides': return <PresentationChart size={size} />;
    case 'summary': return <TextAlignLeft size={size} />;
    case 'adapted': return <Eyeglasses size={size} />;
    case 'worksheet': return <ClipboardText size={size} />;
    case 'link': {
      if (linkKind === 'youtube') return <YoutubeLogo size={size} />;
      if (linkKind === 'drive') return <GoogleDriveLogo size={size} />;
      if (linkKind === 'genially') return <MonitorPlay size={size} />;
      if (linkKind === 'canva') return <PaintBrush size={size} />;
      if (linkKind === 'wordwall') return <PuzzlePiece size={size} />;
      return <LinkSimple size={size} />;
    }
    default: {
      const ext = (filename ?? '').split('.').pop()?.toLowerCase();
      if (ext && ['png', 'jpg', 'jpeg', 'webp', 'heic'].includes(ext)) return <ImageSquare size={size} />;
      if (ext === 'pdf' || ext === 'docx' || ext === 'txt') return <FileText size={size} />;
      if (ext === 'pptx') return <PresentationChart size={size} />;
      return <Paperclip size={size} />;
    }
  }
}

export const WORKSHEET_KIND_LABEL: Record<string, string> = { refuerzo: 'refuerzo', practica: 'práctica', ampliacion: 'ampliación' };

const LINK_LABEL: Record<LinkKind, string> = {
  youtube: 'Vídeo de YouTube', drive: 'Google Drive', genially: 'Genially', canva: 'Canva', wordwall: 'Wordwall', web: 'Enlace',
};

/** "Ficha de refuerzo", "Apuntes", "Vídeo de YouTube"… */
export function kindLabel(m: Pick<Material, 'kind' | 'options'> & { link_kind?: LinkKind | null }): string {
  if (m.kind === 'worksheet') return `Ficha de ${WORKSHEET_KIND_LABEL[String(m.options?.worksheet_kind ?? 'practica')] ?? 'práctica'}`;
  if (m.kind === 'link') return LINK_LABEL[m.link_kind ?? 'web'] ?? 'Enlace';
  return { upload: 'Archivo subido', notes: 'Apuntes', slides: 'Presentación', summary: 'Resumen', adapted: 'Lectura fácil' }[m.kind];
}

/** Generated by Sepia with AI (marked "Borrador IA"), as opposed to the teacher's own files and links. */
export function isGenerated(kind: MaterialKind): boolean {
  return kind !== 'upload' && kind !== 'link';
}
