import {
  ClipboardText, Eyeglasses, FileText, GoogleDriveLogo, ImageSquare, LinkSimple, MonitorPlay, Notebook, PaintBrush, Paperclip,
  PresentationChart, PuzzlePiece, TextAlignLeft, YoutubeLogo,
} from '@phosphor-icons/react';
import type { LinkKind, Material, MaterialKind } from '../../api/units';

/** Line icon for a material kind (uploads: by file extension; links: by site). */
export function MaterialIcon({ kind, filename, linkKind, size = 20 }: {
  kind: MaterialKind; filename?: string; linkKind?: LinkKind | null; size?: number;
}) {
  switch (kind) {
    case 'notes': return <Notebook size={size} />;
    case 'slides': return <PresentationChart size={size} />;
    case 'summary': return <TextAlignLeft size={size} />;
    case 'adapted': return <Eyeglasses size={size} />;
    case 'worksheet': return <ClipboardText size={size} />;
    case 'link': {
      if (linkKind === 'youtube') return <YoutubeLogo size={size} />;
      if (linkKind === 'drive') return <GoogleDriveLogo size={size} />;
      if (linkKind === 'genially') return <MonitorPlay size={size} />;
      if (linkKind === 'canva') return <PaintBrush size={size} />;
      if (linkKind === 'wordwall') return <PuzzlePiece size={size} />;
      return <LinkSimple size={size} />;
    }
    default: {
      const ext = (filename ?? '').split('.').pop()?.toLowerCase();
      if (ext && ['png', 'jpg', 'jpeg', 'webp', 'heic'].includes(ext)) return <ImageSquare size={size} />;
      if (ext === 'pdf' || ext === 'docx' || ext === 'txt') return <FileText size={size} />;
      if (ext === 'pptx') return <PresentationChart size={size} />;
      return <Paperclip size={size} />;
    }
  }
}

const LEVEL_TITLE: Record<string, string> = { refuerzo: 'Ficha de refuerzo', basico: 'Ficha básica', avanzado: 'Ficha de ampliación' };

const LINK_LABEL: Record<LinkKind, string> = {
  youtube: 'Vídeo de YouTube', drive: 'Google Drive', genially: 'Genially', canva: 'Canva', wordwall: 'Wordwall', web: 'Enlace',
};

/** "Ficha de refuerzo", "Apuntes", "Vídeo de YouTube"… (a ficha by its level, as the backend titles it). */
export function kindLabel(m: Pick<Material, 'kind' | 'options'> & { link_kind?: LinkKind | null }): string {
  if (m.kind === 'worksheet') return LEVEL_TITLE[String(m.options?.level ?? '')] ?? 'Ficha de práctica';
  if (m.kind === 'link') return LINK_LABEL[m.link_kind ?? 'web'] ?? 'Enlace';
  return { upload: 'Archivo subido', notes: 'Apuntes', slides: 'Presentación', summary: 'Resumen', adapted: 'Lectura fácil' }[m.kind];
}

/** Generated by Sepia with AI (marked "Borrador IA" until reviewed), as opposed to the teacher's own files and links. */
export function isGenerated(kind: MaterialKind): boolean {
  return kind !== 'upload' && kind !== 'link';
}

/** «Borrador IA» until the teacher edits, rewrites, shares or checks it. */
export function isDraft(m: Pick<Material, 'kind' | 'reviewed' | 'status'>): boolean {
  return isGenerated(m.kind) && m.status === 'ready' && !m.reviewed;
}

/** The title without the unit it belongs to, where the unit is already on screen: «Apuntes · El átomo» → «Apuntes»,
 *  «Ficha de refuerzo · El átomo (2)» → «Ficha de refuerzo (2)». A title the teacher wrote stays as it is. */
export function shortTitle(title: string, unitTitle?: string | null): string {
  if (!unitTitle) return title;
  return title.replace(` · ${unitTitle}`, '').trim() || title;
}

/** «los apuntes», «la ficha de refuerzo», «el resumen»… */
export function withArticle(m: Pick<Material, 'kind' | 'options'>): string {
  const article = m.kind === 'notes' ? 'los' : m.kind === 'summary' ? 'el' : 'la';
  return `${article} ${kindLabel(m).toLowerCase()}`;
}

/** «No se han podido crear los apuntes de «El átomo»». */
export function failedText(m: Pick<Material, 'kind' | 'options'>, unitTitle: string): string {
  return `No se ${m.kind === 'notes' ? 'han' : 'ha'} podido crear ${withArticle(m)} de «${unitTitle}»`;
}

/** «Apuntes de «El átomo» listos», «Presentación de «El átomo» lista». */
export function readyText(m: Pick<Material, 'kind' | 'options'>, unitTitle: string): string {
  const done = m.kind === 'notes' ? 'listos' : m.kind === 'summary' ? 'listo' : 'lista';
  return `${kindLabel(m)} de «${unitTitle}» ${done}`;
}
